### ISSUE TITLE
Adding new styles from highlight.js

### ISSUE THREAD

**Issue by RonithK** [smittytone/HighlighterSwift#1]
I'm trying to add new themes to HighlighterSwift.

I attempted to add the github-dark theme by:
1. Copy and pasting github-dark.css from [highlight.js 11.7.0](https://github.com/highlightjs/highlight.js/blob/11.7.0/src/styles/github-dark.css) into HighlighterSwift/Sources/Assets/styles.
2. Including github-dark.css as a copied resource in Package.swift

I would expect this to work since I'm copying a style from highlight.js v11.7.0, which is the same version that HighlighterSwift uses. But the resulting `NSAttributedString` is just colored black.

Any help is appreciated. Thanks!

**Comment by smittytone** [comment]
There are some quirks in the formatting of highlight.js' style files. I encountered these in the early days of development, and had to tweak some of them. Let me take a look at the github-dark theme and see what might be the problem.

**Comment by smittytone** [comment]
Released
